MobileEComm/Controllers/Admin/AuthController.cs
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using Services.Infrastructure.Interfaces;
using Services.Users.Criteria;

namespace MobileEComm.Controllers.Admin
{
    public class AuthController : Controller
    {
        private readonly IQueryBuilder _queryBuilder;
        public AuthController(IQueryBuilder queryBuilder)
        {
            _queryBuilder = queryBuilder;
        }

        public ActionResult Index(string login, string returnUrl, string errorText)
        {
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.Login = login;
            ViewBag.ErrorText = errorText;
            return View("~/Views/Admin/Auth/Index.cshtml");
        }

        public ActionResult In(string login, string password, string returnUrl)
        {
            var res = _queryBuilder.For<bool>().With(new ValidateUserPasswordCriterion {Email = login, Password = password});
            if (!res)
                return RedirectToAction("Index",
                    new RouteValueDictionary
                    {
                        {"returnUrl", returnUrl},
                        {"login", login},
                        {"errorText", "Не верный логин/пароль"}
                    });
            

            FormsAuthentication.SetAuthCookie(login, true);

            return Redirect(string.IsNullOrEmpty(returnUrl) ? Url.Action("Index", "Main") : returnUrl);
        }

        [Authorize]
        public ActionResult Out()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

MobileEComm/Views/AdminLayout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i,900,900i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="~/content/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/content/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="~/content/css/dashboard.css">
        <link rel="stylesheet" href="~/content/css/bootstrap-clockpicker.min.css"/>
        <link rel="stylesheet" href="~/content/css/bootstrap-colorpicker.min.css"/>
        <link rel="stylesheet" href="~/content/css/bootstrap-datepicker3.standalone.min.css" />
        <link rel="stylesheet" href="~/content/css/jquery.treegrid.css" />
        <link rel="stylesheet" href="~/content/css/bootstrap-editable.css" />
        <link rel="stylesheet" href="~/content/css/jquery.fileupload.css" />
        <link rel="stylesheet" href="~/content/css/bootstrap-dialog.min.css"/>
        <link rel="stylesheet" href="~/content/css/colorbox.css" />
        <link rel="stylesheet" href="~/content/css/action-button.css" />

        @if (IsSectionDefined("Css"))
        {
            @RenderSection("Css", required: false)
        }
        <link rel="stylesheet" href="~/content/css/app.css" />

        <script src="~/content/js/jquery.min.js"></script>
        <script src="~/content/js/bootstrap.min.js"></script>
        <script src="~/content/js/bootstrap-clockpicker.min.js"></script>
        <script src="~/content/js/bootstrap-colorpicker.min.js"></script>
        <script src="~/content/js/bootstrap-datepicker.min.js"></script>
        <script src="~/content/js/bootstrap-datepicker.ru.min.js"></script>
        <script src="~/content/js/bootstrap-dialog.min.js"></script>
        <script src="~/content/js/jquery.treegrid.min.js"></script>
        <script src="~/content/js/jquery.treegrid.bootstrap3.js"></script>
        <script src="~/content/js/bootstrap-editable.min.js"></script>
        <script src="~/content/js/jquery.blockUI.js"></script>
        <script src="~/content/js/jquery.iframe-transport.js"></script>
        <script src="~/content/js/jquery.ui.widget.js"></script>
        <script src="~/content/js/jquery.fileupload.js"></script>
        <script src="~/content/js/jquery.colorbox-min.js"></script>
        <script src="~/content/js/loader.js"></script>
        <script src="~/content/js/sort.js"></script>
        <script src="~/content/js/select.js"></script>
        <script src="~/content/js/object-work.js"></script>
        <script src="~/content/js/pagination.js"></script>
        <script src="~/content/js/filter.js"></script>
        <script src="~/content/js/rivets.bundled.min.js"></script>
        <script src="~/content/js/action-button.js"></script>
        <script src='//cdn.tinymce.com/4/tinymce.min.js'></script>
        
        @if (IsSectionDefined("Js"))
        {
            @RenderSection("Js", required: false)
        }
    </head>
    <body>
        
        <script>
            $(document).ready(function (){
                $('.clockpicker').clockpicker({
                    align: 'left',
                    donetext: 'Выбрать',
                    autoclose: true
                });
            });
        </script>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    @*<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>*@
                    <a class="navbar-brand" href="">@ViewBag.Title</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a>@System.Web.HttpContext.Current.User.Identity.Name</a></li>
                        <li><a href="@Url.Action("Out","Auth")">Выход</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    @Html.Action("MainMenu", "Main")
                </div>
                <div class="col-sm-8 col-sm-offset-3 col-md-9 col-md-offset-2 main">
                    @Html.MvcSiteMap().SiteMapPath()
                    @RenderBody()
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal-loader" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm text-center">
                <div class="modal-content">
                    <div class="modal-body">
                        <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>
                        <span>Загрузка данных...</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Select Modal -->
        <div class="modal fade" id="select-modal" tabindex="-1" role="dialog" aria-labelledby="select-modal-form">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="btn btn-success multiple-apply" style="display: none">Выбрать</button>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="select-modal-title"></h4>
                    </div>
                    <div class="modal-body" id="select-modal-content">
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
    <!-- Select Modal -->
    <!--Action Button-->
    <section class="FAB" style="display: none;">
        <div class="FAB__action-button">
            <i class="action-button__icon material-icons">save</i>
            <p class="action-button__text--hide">Сохранить</p>
        </div>
    </section>
    <!--Action Button-->
    </body>
</html>