MobileEComm/Controllers/Admin/CategoriesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Domain;
using Domain.Dto;
using DomainTranslators;
using Services.Category.Criteria;
using Services.Infrastructure.Interfaces;

namespace MobileEComm.Controllers.Admin
{
    [Authorize]
    public class CategoriesController : BaseObjectCrudController<Category, CategoryDto>
    {

        public CategoriesController(IQueryBuilder queryBuilder, ICommandBuilder commandBuilder, ITranslatorBuilder translator)
            : base(queryBuilder, commandBuilder, translator, "Categories")
        {
        }

        private IEnumerable<CategoryDto> Categories
        {
            get
            {
                return
                    QueryBuilder.For<ICollection<Category>>()
                        .With(new CategoriesCriterion {WithChildren = true})
                        .Select(Translator.Map<Category, CategoryDto>);
            }
        }

        public override ActionResult Index()
        {
            return Index(new CategoriesCriterion{WithChildren = true});
        }

        public override ActionResult IndexData()
        {
            return IndexData(new CategoriesCriterion { WithChildren = true });
        }

        public override ActionResult Add()
        {
            ViewData["Categories"] = Categories;
            return base.Add();
        }

        public override ActionResult Add(CategoryDto o)
        {
            ViewData["Categories"] = Categories;
              
            return base.Add(o);
        }

        public override ActionResult Edit(ulong objectId)
        {
            ViewData["Categories"] = Categories;

            return Edit(new CategoriesCriterion {Ids =  new List<ulong> {objectId}});
        }

        public override ActionResult SetOrder(ulong pk, ulong value)
        {
            base.SetOrder(pk, value);
            return IndexData();
        }
    }
}

MobileEComm/Controllers/Admin/UtilsController.cs
using System.Web.Mvc;
using Utils;

namespace MobileEComm.Controllers.Admin
{
    public class UtilsController : Controller
    {
        public string Transliterate(string text)
        {
            return Transliteration.Front(text);
        }

    }
}

MobileEComm/Views/Admin/Categories/Add.cshtml
@using Domain.Dto
@using FluentBootstrap
@model CategoryDto

@{
    ViewBag.Title = Model == null || Model.Id == 0 ? "Добавление новой категории" : "Редактирование категории";
    Layout = "~/Views/AdminLayout.cshtml";

    if (Model != null && ViewData["Categories"] is IEnumerable<CategoryDto>)
    {
        ViewData["Categories"] = new SelectList((new List<CategoryDto> {new CategoryDto {Id = 0, Name = ""}}).Union(ViewData["Categories"] as IEnumerable<CategoryDto>), "Id", "Name", Model.ParentId);
    }
}

<h2>@ViewBag.Title</h2>

@using (var form = Html.Bootstrap(Model).Form().SetAction("Add", "Categories").Begin())
{
    using (var vGroup = form.FormGroup().Begin())
    {
        @vGroup.ValidationSummary()
    }

    @form.HiddenFor(m=>m.Id)
    @form.HiddenFor(m=>m.SortOrder)
    
    @form.EditorFor(m => m.Name)
    <div class="form-group">
        <label class="control-label">Символьный код</label>
        <div class="input-group">
            <input name="Code" type="text" class="form-control" value="@Model.Code">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="$.get('@(Url.Action("Transliterate","Utils"))', {text: $('input[name=Name]').val()}).done(function(res){$('input[name=Code]').val(res)});">
                    <i class="glyphicon glyphicon-text-width"></i>
                </button>
            </span>
        </div>
    </div>

    using (form.FormGroup().Begin())
    {
        <label class="control-label">Изображение</label>
        <div class="row bottom-buffer">
            <div class="col-sm-12">
                <input type="hidden" name="ImageId" class="form-control" value="@Model.ImageId">
                <button class="btn btn-success" type="button" onclick="SelectModal('Images').done(function (id) { $('input[name=ImageId]').val(id); if (lastSelectItem) { $('#image').attr('src', (lastSelectItem.Path.indexOf('http') !== -1 ? '' : '') + lastSelectItem.Path); }; })">Выбрать</button>
                <button class="btn btn-warning" type="button" onclick="$('input[name=ImageId]').val('0'); $('#image').attr('src', '');">Очистить</button>
            </div>
        </div>
        <div class="row">
            <div class=" col-sm-12">
                <img class="img-thumbnail" id="image" src="@(( string.IsNullOrEmpty(Model.ImagePath) || Model.ImagePath.Contains("http") ? "" : "") + Model.ImagePath)" alt=""/>
            </div>
        </div>
    }

    @form.SelectFor(m=>m.ParentId,ViewData["Categories"] as SelectList)

    @form.Submit("Сохранить")
}

MobileEComm/Views/Admin/Categories/Index.cshtml
@using FluentBootstrap
@model List<Domain.Dto.CategoryDto>
@{
    ViewBag.Title = "Категории";
    Layout = "~/Views/AdminLayout.cshtml";
}

<script>
    $(document).ready(function() {

        $(document).on('click', '.object-row', function() {
            EditObjectView("@Url.Action("Edit", "Categories")", $(this).attr("data-object-id"));
        });

        $(document).on('click', ".object-row-remove", function () {
            DeleteObject("@Url.Action("Delete", "Categories")", "@Url.Action("IndexData", "Categories")", $(this).attr("data-object-id"), "#categories-table")
                .fail(function() {
                    BootstrapDialog.show({
                        type: BootstrapDialog.TYPE_DANGER,
                        title: 'Ошибка',
                        message: 'Не возможно удалить объект, проверьте связи этого объекта'
                    });

                    $(".tree-grid").treegrid();
                    $(".editable").editable({ url: setSortOrder });

                })
                .done(function() {
                    $(".tree-grid").treegrid();
                    $(".editable").editable({ url: setSortOrder });
                });

            $(".tree-grid").treegrid();
            $(".editable").editable({ url: setSortOrder });
        });

        $(".tree-grid").treegrid();
        $(".editable").editable({ url: setSortOrder });
    });

    function setSortOrder(params) {
        var d = new $.Deferred();

        showModalLoader('#categories-table');

        $.post('@Url.Action("SetOrder","Categories")', { pk: params.pk, value: params.value }).done(function(result) {
            $('#categories-table').replaceWith(result);

            $(".tree-grid").treegrid();
            $(".editable").editable({ url: setSortOrder });

            hideModalLoader('#categories-table');
        }).fail(function() {});

        return d.promise();
    }
</script>

<h2>@ViewBag.Title</h2>
@using (var toolbar = Html.Bootstrap().ButtonToolbar().Begin())
{
    using (var group = toolbar.ButtonGroup().Begin())
    {
        @group.LinkButton(" Добавить", Url.Action("Add", "Categories")).SetState(ButtonState.Success).AddContent(Html.Bootstrap().Span().AddCss("glyphicon glyphicon-plus"))
    }
}
<hr />
<br />

@Html.Partial("~/Views/Admin/Categories/IndexData.cshtml", Model)

MobileEComm/Views/Admin/Categories/IndexData.cshtml
@using Domain.Dto
@using FluentBootstrap
@using FluentBootstrap.Mvc
@using FluentBootstrap.Tables
@model List<CategoryDto>

<script>
        var selectData = {
            @foreach (var category in Model)
            {
                @Html.Raw(string.Format("'{0}':{{ Id:'{0}', Code:'{1}', Name:'{2}' }},", category.Id, category.Code, category.Name))
            }

        };
</script>

@{
    var childCats = Model.Where(c => c.ParentId > 0).ToList();
    var parentCats = Model.Where(c => c.ParentId == null).ToList().OrderBy(c=>c.SortOrder).ToList();
    
}
@helper  MakeRow(ComponentWrapper<MvcBootstrapConfig<List<CategoryDto>>, Table> table, CategoryDto category, List<CategoryDto> childCategories)
{
    @table.TableDataRow(category.Name, Html.Bootstrap().Link(category.SortOrder.ToString()
        ).AddAttributes(new Dictionary<string, object>
        {
            {"data-name", "sort-order"}, {"data-original-title", "Изменить сортировку"},
            {"data-inputclass", "span1"}, {"data-mode", "inline"},
            {"data-pk", category.Id}
        }
                ).AddCss("editable"),
        Html.Bootstrap().CenterBlock().AddContent(
            Html.Bootstrap().Span().AddCss("glyphicon glyphicon-pencil object-row pointer hide-in-select").AddAttribute("data-object-id", category.Id)
            ).AddContent(Html.Bootstrap().Span().AddCss("glyphicon glyphicon-remove object-row-remove pointer hide-in-select").AddAttribute("data-object-id", category.Id)
            ).AddContent(Html.Bootstrap().CheckBox().AddCss("multiple-selector").AddStyle("display", "none").AddAttribute("data-object-id", category.Id))
        ).AddCss("pointer selectable").AddAttribute("data-object-id", category.Id).AddCss("treegrid-" + category.Id).AddCss(category.ParentId > 0 ? "treegrid-parent-" + category.ParentId : "").AddCss("tr-last-child-text-center")

    if (childCategories.All(c => c.ParentId != category.Id))
    {
        return;
    }

    var childs = childCategories.Where(c => c.ParentId == category.Id).OrderBy(c => c.SortOrder).ToList();

    foreach (var childCategory in childs)
    {
        @MakeRow(table, childCategory, childCategories)
    }
}

@using (var table = Html.Bootstrap().Table().SetStyle(TableStyle.Bordered | TableStyle.Hover).SetAlignment(TextAlignment.Left).AddCss("tree-grid").AddAttribute("Id", "categories-table").Begin())
{
    @table.TableHeaderRow("Название", "Сортировка", "").SetAlignment(TextAlignment.Center)

    foreach (var category in parentCats)
    {
        @MakeRow(table, category, childCats);
    }

}